version: '3'

services:
  nginx:
    image: nginx
    container_name: reverse-proxy
    network_mode: host
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx-logs:/var/log/nginx
    command: /bin/sh -c "chmod -R 755 /var/log/nginx && nginx -g 'daemon off;'"
    restart: unless-stopped
